### ISSUE TITLE
File not uploading but multer not giving me any errors

### ISSUE THREAD

**Issue by minu-aswanth** [expressjs/multer#391] opened 2016-09-22 12:41 UTC
I am trying to upload a file. The file does not get uploaded but multer does not give me any errors.

``` js
var storage = multer.diskStorage({
  destination: function (req, file, cb) {
    console.log("Hello people in storage");
    return cb(null, 'client/assets/uploads');
  },
  filename: function (req, file, cb) {
    var ext = file.mimetype.split('/')[1];
    return cb(null, Hello + '-' + Date.now() + "." + ext);
  }
})
```

In fact, it does not even go to the console.log line. Can you help me please?

**Comment by LinusU** [comment] 2016-09-22 13:10
How are you using `storage`?

**Comment by minu-aswanth** [comment] 2016-09-22 13:11
`var upload = multer({ storage: storage, limits: {fileSize: 1000000}});
router.post('/upload', upload.single('file'), controller.create);`

**Comment by minu-aswanth** [comment] 2016-09-22 13:18
This same code works in another of my project. Maybe some other modules are messing up with this?

**Comment by SHAPPY0** [comment] 2016-10-25 17:59
hi, I am also facing the same problem.... if u got the solution then plz share with me.. I already wasted my 3 days in this problem.

thanks

**Comment by minu-aswanth** [comment] 2016-10-26 01:46
@SHAPPY0 , I started a new project and it works fine in that.

**Comment by SHAPPY0** [comment] 2016-10-26 04:29
But I can't change project... If you get any solution then let me know.. Please.

**Comment by dadixon** [comment] 2016-11-04 16:00
I'm having a similar issue. I get no errors when uploading but the file never uploads. Don't know where it is. I'm using a basic example

`var multer = require('multer');
var upload = multer({dest: 'public/uploads'});`

`router.post('/testimage', upload.single('myImage'), function(req, res, next) {
    if (req.file) {
        console.dir(req.file);
        return res.end('Thank you for the file');
    }
    res.end('Missing file');
});`

I see the Thank you message with no errors but when I look in the directory (public/uploads) there's nothing there.

**Comment by dadixon** [comment] 2016-11-04 17:24
I'm running nginx so that's my issue.

**Comment by Grantlyk** [comment] 2017-01-11 14:13
I'm having this same issue, but my req.file and req.body objects are both undefined

**Comment by SHAPPY0** [comment] 2017-01-11 14:15
Hi @grantlyk,

Are u using angular.js at the front end????

**Comment by Grantlyk** [comment] 2017-01-11 14:20
@SHAPPY0 No i'm not however I have done so in the past with multer, I was literally just about to post here again saying i've resolved my issue. my problem is that I was using postman to test my API endpoint and it was specifying the content type `application/json` rather than `multipart/form-data`

Are you still having your issue?

**Comment by SHAPPY0** [comment] 2017-01-11 14:48
@Grantlyk, 
No , i also solved my issue.... I was using angular.js so I had need to send file from front to back end using angular.js
I found a solution and solved it.

Cheers

**Comment by thoshith** [comment] 2017-03-27 22:43
Facing same problem here.. No error and doesn't work. Every time it just creates empty folder.
Can somebody please help.

```const storage = multer.diskStorage({
    destination: function (req, file, cb) {
        cb(null, 'uploads/')
    },
    filename: function (req, file, cb) {
        cb(null, file.originalname)
    }
})


var uploading =  multer({storage: storage}).single('file');



module.exports = function (router) {
    router.route("/upload").post(uploading, function (req, res, next) {
        uploading(req, res, function (err) {
            if (err) {
               console.log(err);
            }
            res.send('Successfully uploaded ' + req.files.length + ' files!');
        })

    });
};```

**Comment by Hanzofm** [comment] 2017-05-26 11:19
Facing same problem here:

**I'm using on backend:**

Multer: 1.3.0
Express and Express router

**And in frontend:**

 Angular 4.1.3 with ng2-file-upload 1.2.1


```
var storage = multer.diskStorage({
    destination: function (req, file, cb) {
        cb(null, './uploads/')
    },
    filename: function (req, file, cb) {
        console.log("aha " + file.originalname);
        cb(null, file.originalname)
    }
})


var upload = multer({ storage: storage })

router.post('/uploadPhoto', upload.single('file'), function(req, res, next) { 
console.dir(req.file); //this returns undefined

console.log(done)
res.status(200).json({done: done})
}
```

Any idea, or someone solved the problem?

**Comment by Grantlyk** [comment] 2017-05-26 13:21
Might be a better idea to post your front end code, chances are it's the wrong content type

**Comment by Hanzofm** [comment] 2017-05-26 20:01
You 're right Grantlyk, I've updated my original message with more info of frontend and backend

**Comment by Sunjay10it29** [comment] 2017-06-27 03:38
Dear Guys I had same problem and I resolved by just replacing the path of uploads
cb(null, 'uploads/') wrong
cb(null, './uploads/') correct 

so I got my file uploaded

**Comment by Eksapsy** [comment] 2017-09-13 23:15
Having the same problem. What I've got so far is:
## Backend:

```
const path = require('path');
const multer = require('multer');
const upload = multer( { dest: '../uploads/' } ); // Double '.' to get out of Routes folder

module.exports = (app) => {

	app.post(
			'/api/upload',
			upload.single('file'),
			(req, res) => {
				console.log("File Uploaded Succesfully!"); // Well ... I wish :P
				console.log(req.file); // Undefined
				console.log(req.files); // Undefined
				console.log(req.body.file); // Undefined
				console.log(req.body.files); // Undefined
				res.send('File Uploaded Successfully!');
			}
	)
};

```

## Frontend
I'm using **Dropzone** & **Axios** on this one

```
onDrop(files) {
	console.log(files);
	axios.post('/api/upload', {files});
}

render() { 
return ( 
<Dropzone
	accept='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
	onDrop={this.onDrop}
>
	Drop Excel Files here
</Dropzone>
);
```

No errors, the Backend shows all these messages I **console.log**-ed. But all 4 of the **req** console logs showed **undefined**. And no file was actually uploaded in the disk. Nothing.


Tried **Postman**. And actually understood that I don't even understand the background problem so well. 

In **form-data** it just returned **error** of **unexpected field**.
In **binary** it was done successfully, but the file wasn't uploaded ... as expected. Which is basically the same behavior with **Dropzone**.

**Comment by scsureshWeb** [comment] 2017-09-19 09:25
Hi Guys

**Comment by dpkswn4** [comment] 2017-09-19 14:20
Use "Accept": "application/json".

Remove "Application-Type": "application/json"

It will work

**Comment by curiousalok** [comment] 2017-09-27 07:37
Hi Guys
Faceing same issue while uploading without error works prefectly in local but not server @dadixon have you fixed issue

**Comment by curiousalok** [comment] 2017-09-27 07:43
i am using multer to upload files it is working perfectly on local machine but when service is hosted on cloud server and file is uploaded from local machine the multer is creating a file with the file name with size 0 kb can anbody tell me what i am doing wrong?

my front end is C# windows application.

**Comment by iyunusov** [comment] 2017-11-27 08:28
Guys, I was having the same problem - "No errors, but file does not upload". 
I found that I forgot adding enctype attribute equalling to "multipart/form-data".
Though I didn't find any information about html code on multer description, your html should look something like:
    `<form class="" enctype="multipart/form-data" action="/imageUploader/loggedIn" method="post">
      <input type="file" name="photo" value="" />
      <button type="submit" name="button">Submit</button>
    </form>`

**Comment by scsureshWeb** [comment] 2017-11-27 08:47
file will be upload in your root folder path.

**Comment by kas2000** [comment] 2017-11-29 07:33
I also had this kind of issue. It didn't even give me any errors and everything seemed okay, however multer didn't save my images. You probably face this problem because of routing. I had server.js file and its route index.js in another folder. I thought that i had to set a destination according to location of index.js, but you should set a destination according to where your server.js is located! Hope it will help you!

**Comment by abhijeet1403** [comment] 2018-01-18 20:22
2 things 
1. Make sure the folder you're trying to save to is already created. Node will not create it for you if it does not exists.  if you're using storage. (It will if you're using *dest*)
2. As @Sunjay10it29  pointed out Make sure the folder name is 
cb(null, './uploads/') instead of cb(null, 'uploads/')

**Comment by cesarbuenrostro-tiempodev** [comment] 2018-01-26 09:39
just need resolve the path, try this. 
`
const storage = multer.diskStorage({
  destination: function (req, file, cb) {
    cb(null, path.resolve(__dirname, './test'))
  },
  filename: function (req, file, cb) {
    cb(null, file.originalname)
  }
})
`

whit <3 Cesar.

**Comment by shystruk** [comment] 2018-03-12 14:41
Hi all,

For me, the folder was created "uploads" and I got File object in req.files.file, but file is not saved into uploads folder and File path is "/var/folders/82/3s2yq3zj77l3xn1xvy9pgfx40000gn/T/upload_6bcd336e42b32122a8ed682e52ab". 
I use restify. 

```javascript
const upload = multer({dest: 'uploads/'})

server.post({ path: "photo", version }, upload.single('file'), this.savePhoto.bind(this))

savePhoto(req, res, next) {
    console.log('FILE: ', req.files.file)

    res.json(200, {})
    return next()
  }
```

**Comment by LinusU** [comment] 2018-03-12 17:52
@shystruk you probably want to look at `req.file`, instead of `req.files.file` 👍

**Comment by shystruk** [comment] 2018-03-12 17:59
@LinusU 
```javascript
console.log('FILE: ', req.file) => undefined
```

**Comment by danndav** [comment] 2018-03-26 18:22
this issue is not yet solved...pls guys am also having the same problem here...

**Comment by shystruk** [comment] 2018-03-26 20:11
@danndav 
I did it in a native way. Works fine for one file. I use AWS S3 bucket for saving files.

```javascript
fs.readFile(req.files.file.path, (err, fileData) => {
 // => fileData [Buffer]          
})
```

**Comment by khan990** [comment] 2018-04-22 13:39
It took complete one night for me to resolve. It was conflicting with another package `require('express-fileupload');`
Uninstalled it. And multer worked fine as expected.

**Comment by tvnhan** [comment] 2018-05-20 09:19
Hi,
I got same issue.
I used postman to send request. 
`// server.js

// set up ======================================================================
// get all the tools we need
var express = require('express');
var app = express();
var port = process.env.PORT || 4000;

var multer  = require('multer')


// var morgan = require('morgan');
// var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');
// var session = require('express-session');

  var storageOptions = multer.diskStorage({
    destination: function (req, file, cb) {
      cb(null, './useravatars/')
    },
    filename: function (req, file, cb) {
      cb(null, file.fieldname + '-' + Date.now())
    }
  });
  
  var avatarUpload = multer({
      storage: storageOptions,
      limits: {
          fileSize: 1000000
      }
  }).single("avatar");


app.use(bodyParser.json()); // get information from html forms
app.use(bodyParser.urlencoded({
    extended: true
}));

// routes ======================================================================
app.post('/profile', avatarUpload, function (req, res, next) {
    // req.file is the `avatar` file
    // req.body will hold the text fields, if there were any
    console.log(req.file);
    return res.send({});
})


// launch ======================================================================
app.listen(port);
console.log('The magic happens on port ' + port);`

I tried all suggestion above but it still not working. 
Any idea for this?

**Comment by Matar91** [comment] 2018-05-21 01:10
Same problem. Removing the filename, storage passed inside multer works... But i need the filename

**Comment by nahid597** [comment] 2018-05-27 18:26
const storage = multer.diskStorage({

    destrination: function(req, file, cb) {
        cb(null, path.resolve(__dirname, './uploads/'));
    },
    filename: function(req, file, cb) {
        cb(null, new Date().toISOString() + file.originalname);
    }
});

const upload = multer({ storage: storage });

it's can not work for me..


after this i get path

 path: '/tmp/2018-05-27T18:18:45.184ZScreenshot from 2018-05-17 10-26-39.png',

through i want to store image or file in uploads folder.

**Comment by remoteportal** [comment] 2018-07-03 09:29
solved: I forgot:
enctype="multipart/form-data"
in my HTML form.

**Comment by okonsemi** [comment] 2018-08-07 18:57
the same issue here. Would be helpful at least to add some check(s), so it'll be less confusing and more transparent

**Comment by okonsemi** [comment] 2018-08-08 21:08
solution (be explicit in the upload object ):

```
global.upload2 = multer({
  storage: multer.diskStorage({
    destination: (req, file, cb) => {
        cb(null, path.join(root, 'dest2'));
    },
    filename: (req, file, cb) => {
        const newFilename = file.originalname;
        cb(null, newFilename);
    },
  })
});
```

**Comment by AdamT213** [comment] 2018-08-10 21:44
Are there other packages that multer is known to conflict with? I am using multer on one route and it doesn't seem to be doing anything at all. I am just trying to parse a text file, but req.file and req.files are both undefined?

**Comment by shivasurya** [comment] 2018-09-06 04:53
Guys if you face such error, kindly check the content type set from front end/ postman before making a request.

**Comment by mandaputtra** [comment] 2018-10-09 14:13
> I think this problem happens because of windows not allowed ':' in filename.

yeah you right!

**Comment by gabriel9130** [comment] 2018-10-10 20:59
same problem here, and I copied examples from the web. I assure that the name of my file to upload is the same as what is passed to the upload function. Nothing happend, no error but no file is saved. The folder is also not created.

var express = require('express');
let crypto = require('crypto');
var router = express.Router();
let multer = require('multer');
let fs = require('fs-extra');

let upload = multer({
  storage: multer.diskStorage({
    destination: (req, file, callback) => {
      let path = `./uploads/` + crypto.randomBytes(12);
      fs.mkdirsSync(path);
      callback(null, path);
    },
    filename: (req, file, callback) => {
      //originalname is the uploaded file's name with extn
      callback(null, file.originalname);
    }
  })
});
/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('main');
});

router.get('/twoFacesMorphingForm', function(req, res, next) {
  res.render('twoFacesMorphingForm');
});

router.post('/twoFacesMorphingRes', upload.single('img1'),
             function(req, res, next) {
  res.render('twoFacesMorphingRes');
});

**Comment by AymerFi** [comment] 2018-11-28 17:14
I had a very similar issue: was that apparently it is not recognised as a file by Multer if there is no .csv as key (extension file):

https://stackoverflow.com/questions/31734164/how-do-i-send-a-file-from-postman-to-node-js-with-multer

hope it helps,

**Comment by evmdev** [comment] 2018-12-24 10:55
delete it module

**Comment by savula1** [comment] 2019-02-26 03:38
Upload works fine in my local server, exact same code does not work on company server. Upload returns no error but no file uploads.

**Comment by Xugai** [comment] 2019-03-04 04:02
> It took complete one night for me to resolve. It was conflicting with another package `require('express-fileupload');`
> Uninstalled it. And multer worked fine as expected.

wow, you are awesome! my project had the same issue and it's reason just match your explain!

**Comment by AdamT213** [comment] 2019-03-04 15:46
To anyone having issues configuring multer to work with other express middlewares, check out this [blog post](https://medium.com/@adt6261/handling-file-upload-and-parse-async-in-node-js-884c2a7cf8c4) I wrote on the topic, you might find it useful.

**Comment by anthonyalayo** [comment] 2019-04-25 19:33
I also got stuck on this. The big gotcha was that the more trivial initialization of the uploader uses "dest" as a key whereas the object initialization (where you can set the filename to be not random) uses "destination" as a key.

`multer({dest: './uploads/'});`

versus

```
const uploadStorageConfig = multer.diskStorage({
  destination: './uploads/',
  filename: (req, file, callback) => {
    callback(null, file.originalname);
  },
});
```

**Comment by plmnjo** [comment] 2019-04-25 20:32
"Whoops! That unsubscribe link isn't valid for your account."
Unsubscribe, please

**Comment by WaseemAhmadNaeem** [comment] 2019-04-26 10:52
> 
> 
> Hi,
> I got same issue.
> I used postman to send request.
> Here my code: https://paste.ofcode.org/QQj9gG3HACVsbkqmsqQwzE
> I tried all suggestion above but it still not working.
> If i use `var upload = multer({ dest: 'uploads/' })`, it work.
> Any idea for this?

I am also using PostMan for sending requests and using the code snippt you mentioned is working..
failed in my case

**Comment by bharath619** [comment] 2019-06-03 07:54
> 
> 
> in windows server I also had this problem. Change filename callback function
> 
> ```js
>  cb(null, new Date().toISOString() + file.originalname);
> ```
> 
> to
> 
> ```js
> cb(null, new Date().toISOString().replace(/[-T:\.Z]/g, "") + file.originalname);
> ```
> 
> I think this problem happens because of windows not allowed ':' in filename.

thank you!!! this is really working :)

**Comment by plmnjo** [comment] 2019-06-03 17:39
unsubscribe

**Closed** 2019-06-11 14:25 UTC

**Comment by akashgangrade** [comment] 2019-07-26 05:17
I am facing the same issue, not able to upload image using multer.

**Comment by akashgangrade** [comment] 2019-07-26 06:33
Try using Busboy instead of Multer to upload any file. Refer this article for more info. It is working fine.

**Comment by japhet98** [comment] 2019-10-25 17:03
`<form id        =  "uploadForm"
     enctype   =  "multipart/form-data"
     action    =  "/api/photo"
     method    =  "post"
>`
without the **multipart/form-data,** file will not be uploaded.

**Comment by coolamber-stevneves** [comment] 2019-11-15 09:36
I had a similar problem, no errors, no file uploaded, found out it was the cache with the angular service worker that was causing the issue. If I disable the cache it just works, wonder if there's a solution for this.

**Comment by joeldmyers** [comment] 2020-02-28 19:31
> I'm running nginx so that's my issue.

Thanks so much @dadixon  for the nginx mention; I was going a bit crazy there trying to figure out the source of the error.

For anyone else using nginx and not getting an error, you can update your nginx config: 

`sudo nano /etc/nginx/nginx.conf`

Then under the `http {`  assuming you are using http; mine is an ec2 connected to a load balancer for https): 

add the line 
`client_max_body_size 8M` or whatever you want the limit to be.
then reload nginx, which varies depending on your server type.

**Comment by tranlenhatbinh** [comment] 2020-04-06 03:47
> Uninstalled it. And multer worked fine as expected.

Thanks,  I apply the way as you suggested and it works now.

**Comment by ssamateh** [comment] 2020-04-06 18:29
If you are using multer  in a Google Cloud Function. Check solution on [stackoverflow](https://stackoverflow.com/questions/47242340/how-to-perform-an-http-file-upload-using-express-on-cloud-functions-for-firebase/61065117#61065117)

**Comment by plmnjo** [comment] 2020-04-06 18:35
PLEASE STOP SPAMMING ME

and fix the bug: "Whoops! That unsubscribe link isn't valid for your account."

**Comment by mandaputtra** [comment] 2020-04-06 22:14
@plmnjo you can click those unsubs button on the issue man :rofl:

**Comment by helderburato** [comment] 2020-04-25 20:33
I did this config and worked fine:

```js
import multer from 'multer';
import crypto from 'crypto';
import { extname, resolve } from 'path';

const multerConfig = {
  storage: multer.diskStorage({
    destination: resolve(__dirname, '..', '..', 'tmp', 'uploads'),
    filename: (req, file, cb) => {
      crypto.randomBytes(16, (err, res) => {
        if (err) {
          return cb(err);
        }

        return cb(null, res.toString('hex') + extname(file.originalname));
      });
    },
  }),
};

export default multerConfig;
```

Note: The `originalname` word need to be `lowercase`.

**Comment by adamreisnz** [comment] 2020-05-21 02:39
I found the issue to be that Windows was uploading CSV files with content type `application/octet-stream` (inside of multipart/form-data), where as OS X was using `text/csv` as expected.

This discrepancy led multer to discard the file, but it did so without erroring. It simply didn't set `req.file` (using memory storage).

The fix was to modify the file type prior to sending in AngularJS as follows:

```
if (file.type !== 'text/csv') {
  file = file.slice(0, file.size, 'text/csv');
}
```

**Comment by DaveSoham08** [comment] 2020-06-15 15:36
> in windows server I also had this problem. Change filename callback function
> 
> ```js
>  cb(null, new Date().toISOString() + file.originalname);
> ```
> 
> to
> 
> ```js
> cb(null, new Date().toISOString().replace(/[-T:\.Z]/g, "") + file.originalname);
> ```
> 
> I think this problem happens because of windows not allowed ':' in filename.

Thank you @yavuz1986 . That solved my issue

**Comment by drewf7** [comment] 2020-08-31 22:16
I know this is a closed issue. But I wanted to leave my experience here for the next poor soul troubleshooting this bug.

In our case it was a qt frontend sending the files, and I was encountering random failures.

The cause was that qt's multi-part form generation (by default) randomly generates a boundary. If that boundary contains the "/"  character, multer will fail to process the form the form data, but will log no error.

Manually setting a random set of boundary characters fixed the issue.

**Comment by lkenny97** [comment] 2020-09-07 16:37
Same as the guy above, wanna leave my experience in case someone has the same problem.

I was using react-dropzone to get the file. Turns out it gives back an array of files. I set the limit to 1 and thought it is going to be an object and not array for some reason. Sending 0th file in the array from frontend fixed it from me.

**Comment by DukeManh** [comment] 2020-09-12 20:40
> Dear Guys I had same problem and I resolved by just replacing the path of uploads
> cb(null, 'uploads/') wrong
> cb(null, './uploads/') correct
> 
> so I got my file uploaded

Love u so much

**Comment by viru-rishu** [comment] 2020-11-03 06:04
In Our project, The multer file upload was not working, we checked all the above issue solutions, but in vain. Then we checked deeply and found out that whenever the file upload server was taking more than 1 minute the file upload was not working and multer was not giving any error and there was cors issue on the frontend. So you can also check the timeout limit set at your server for issue solution. We changed the timeout limit and our uploads started working.

Thanks

**Comment by vadivelshanmugam** [comment] 2021-02-02 18:39
When I use below code its working for me on Mac.
var storage = multer.diskStorage({
      destination: function (req, file, cb) {
      cb(null, 'public')
    },
    filename: function (req, file, cb) {
      cb(null, Date.now() + '-' +file.originalname )
    }
})
**Note:** request header should file: {binary}

**Comment by SaboSuke** [comment] 2021-03-17 10:19
When I use this code it works fine
`const upload = multer({
    dest: './upload/',
})`

but when I write it this way it bugs with no errors but this `500 (Internal Server Error)`
```
var storage = multer.diskStorage({
    destination: function (req, file, cb) {
        cb(null, 'uploads')
    },
    filename: function (req, file, cb) {
        cb(null, new Date().toISOString().replace(/[-T:\.Z]/g, "") + file.originalname);
    }
})

var upload = multer({ storage: storage })
```
does anyone have an idea why? I've ready all what's above but nothing worked.

**Comment by geomarb** [comment] 2021-04-13 14:58
Same issue here. 
But in my case it is related to "filename" on request side. If I remove **`filename="foo.pdf"`** from the request it puts "pdfFile" in **`req.body`** instead of generate **`req.file`** and here is the problem. In my case I must send **`filename`** to the backend and no mater what I put there since it is not null or empty string, it can be `**"a"**` or any valid string. 
Later on I will have to upload a folder and it might be an issue if I don't figure out how to send **`filename`** for all files when sending  multiple files at once.

Please, let me know if it works for you when you send **filename** in your request?

Check out the what I am using to build the request in VS Code's Rest Cliente plugin: 

`
POST http://localhost:3000/pdf/file
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="pdfFile";  **filename="foo.pdf"**
Content-Type: application/pdf

< /Users/me/Projects/mt/api/files/foo.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW--
`

**Comment by sainanky** [comment] 2021-06-25 16:15
HI i found the issue after hours of debugging you just remove the content-type from the client from where you are calling this api and then this works like a charm.

**Comment by nkemcels** [comment] 2021-06-30 21:16
Saved my day @khan990. I added the `express.raw` middleware which seemed to have been conflicting with `multer`

**Comment by vvs8** [comment] 2021-07-30 20:30
> It took complete one night for me to resolve. It was conflicting with another package `require('express-fileupload');`
> Uninstalled it. And multer worked fine as expected.

Thank you!

**Comment by jwhitty1** [comment] 2021-08-13 08:40
> just need resolve the path, try this.
> 
> ```js
> const storage = multer.diskStorage({
> 
>   destination: function (req, file, cb) {
>     cb(null, path.resolve(__dirname, './test'))
>   },
> 
>   filename: function (req, file, cb) {
>     cb(null, file.originalname)
>   }
> })
> ```
> 
> whit <3 Cesar.

THIS WORKED!! I wasnt getting the files uploaded, then today (a week later) I stumbled upon an uploads folder created OUTSIDE my project root folder (!?) and it had...69 images...hehehe

Anyways after all this crap trying to even recreate this WRONG upload location, changing the path to all of these:
uploads/
/uploads/
./uploads/
../uploads/

Both WITH and WITHOUT the folder being previously created...nothing was working....UNTIL THIS ANSWER!
The path resolution solved everything! THANK YOU!

**Comment by methot-ilya-3ds** [comment] 2021-08-31 20:24
I solved this problem FINALLY! 

Apparently using the `app.use(fileUpload());` middleware was somehow interfering with multer.

Before when I had `app.use(fileUpload());` enabled I could access the file through `req.files`, but the file wouldnt save.

After commenting out `// app.use(fileUpload());` I can access the file through `req.file` and it will save correctly.

**Comment by jwhitty1** [comment] 2021-09-01 07:33
> I solved this problem FINALLY!
> 
> Apparently using the `app.use(fileUpload());` middleware was somehow interfering with multer.
> 
> Before when I had `app.use(fileUpload());` enabled I could access the file through `req.files`, but the file wouldnt save.
> 
> After commenting out `// app.use(fileUpload());` I can access the file through `req.file` and it will save correctly.

As I said before you, I can upload the files now, but they're stored as the "local folder path" and inaccessible as an image using req.file... I wonder if I need to be doing something beyond this now that the actual file is sent to the folder, like referencing the file differently or when I set the "original filename/path name" etc in the POST request, maybe I need to be writing something different?

**Comment by methot-ilya-3ds** [comment] 2021-09-01 18:11
> As I said before you, I can upload the files now, but they're stored as the "local folder path" and inaccessible as an image using req.file... I wonder if I need to be doing something beyond this now that the actual file is sent to the folder, like referencing the file differently or when I set the "original filename/path name" etc in the POST request, maybe I need to be writing something different?

try pasting your current code so we can take a look

**Comment by ravichauhan0407** [comment] 2021-11-02 09:27
I had got same error but now i have fixed it by removing Date() function .
Initial code:
var fileStorage=multer.diskStorage(
    {
        destination:(req,file,cb)=>
        {
            
            cb(null,'images');
        },
        filename:(req,file,cb)=>
        {
            
           cb(null,new Date().toISOString()+'-'+file.originalname)
        }
    }
  )


updated Code:
var fileStorage=multer.diskStorage(
  {
      destination:(req,file,cb)=>
      {
          
          cb(null,'images');
      },
      filename:(req,file,cb)=>
      {
          
         cb(null,file.originalname)
      }
  }
)
// you can use Hash generator for uniqueness of file name .

**Comment by iescalante** [comment] 2021-11-24 22:01
> I had got same error but now i have fixed it by removing Date() function . Initial code: var fileStorage=multer.diskStorage( { destination:(req,file,cb)=> {
> 
> ```
>         cb(null,'images');
>     },
>     filename:(req,file,cb)=>
>     {
>         
>        cb(null,new Date().toISOString()+'-'+file.originalname)
>     }
> }
> ```
> 
> )
> 
> updated Code: var fileStorage=multer.diskStorage( { destination:(req,file,cb)=> {
> 
> ```
>       cb(null,'images');
>   },
>   filename:(req,file,cb)=>
>   {
>       
>      cb(null,file.originalname)
>   }
> ```
> 
> } ) // you can use Hash generator for uniqueness of file name .

This worked for me like a charm, it was simply using Date for the name that caused a lot of issues so I just used Math.random() for the sake of making work

**Comment by sarathlal-iom** [comment] 2022-01-20 11:24
n my project multer in app.js file.now try to use image upload getting error
const multer = require('multer');
const upload = multer();

app.use(upload.array());
comment  app.use(upload.array()); i can upload image but same time my another api's getting error

**Comment by sarathlal-iom** [comment] 2022-01-20 11:26
> I solved this problem FINALLY!
> 
> Apparently using the `app.use(fileUpload());` middleware was somehow interfering with multer.
> 
> Before when I had `app.use(fileUpload());` enabled I could access the file through `req.files`, but the file wouldnt save.
> 
> After commenting out `// app.use(fileUpload());` I can access the file through `req.file` and it will save correctly.

after comment another api's not working becouse using form data array

**Comment by 2diegoduque** [comment] 2022-03-20 18:21
something new?

**Comment by naveenkamath002** [comment] 2022-03-22 17:59
make sure to check your app.routes() in index.js and make sure this app.route() stays at the top.
