### ISSUE TITLE
Promises (await/async) support in Multer 2.0 (MulterError) instead of callback

### ISSUE THREAD

**Issue by pubmikeb** [expressjs/multer#909] opened 2020-06-12 23:10 UTC
To control a size of an uploading files in Multer 2.0.0-rc.2 we can use:
```js
const upload = multer({
	limits: {
		fileSize: CONFIG_STORAGE.uploader.maxFileSizeInBytes
	}
}).single("file");

app.post('/upload', (req, res) => {

	upload(req, res, (err) => {

		if (err) {
			console.error("An error occurred when uploading");
			return;
		}

		console.log("Everything went fine");

	});

})
```

It does work but it uses a callback and it's ugly, especially in 2020+.
Isn't better to provide a **native** promises (aka `await`/`async`) support instead?
Without applying a workaround such as `util/promisify`.

**Comment by ghinks** [comment] 2020-07-10 13:25
Thank you @pubmikeb. This does sound like both a question and an idea for an enhancement. Depending on the workload someone will respond here to discuss this with you. An even better idea is to lookout for the next [technical steering committee](https://github.com/expressjs/discussions/issues) and get involved to speed up the implementation of you idea.

**Comment by seahindeniz** [comment] 2020-11-16 19:05
Similar to #265?

**Comment by pubmikeb** [comment] 2021-05-08 09:02
@ghinks & @seahindeniz, are there any updates?

**Comment by ghinks** [comment] 2021-05-08 09:52
Sorry, I'm no longer active with express and moved to use a different framework

**Comment by LinusU** [comment] 2021-08-06 14:13
Well, since express uses callbacks for the `next` function I'm not sure if we could fix and still be able to use Multer as an express middleware?

Happy to consider this if you could provide a concrete API suggestion 👍

**Comment by pubmikeb** [comment] 2021-08-06 14:34
> if you could provide a concrete API suggestion

Can the the Express.js's callbacks be wrapped with Promises, e.g. :https://stackoverflow.com/a/37104225 ?

**Comment by LinusU** [comment] 2021-08-06 14:51
The problem is that Express will pass us a callback, and expect that callback to be called. But if we instead return a Promise, the request will simply hang...

**Comment by pubmikeb** [comment] 2021-08-06 14:58
Well, then it's a great opportunity to upgrade the entire Express.js codebase to make it ES2021 friendly.

**Comment by LinusU** [comment] 2021-08-06 15:40
Yeah, that would be great 👍 

Closing this as we cannot do anything here until Express.js releases a breaking change that changes `next` to use promises instead of callbacks...

**Closed by LinusU** 2021-08-06 15:41 UTC
Labels: question, ideas
