### ISSUE TITLE
write(string, encoding, offset, length) is deprecated

### ISSUE THREAD

**Issue by niravjgandhi** [expressjs/multer#137] opened 2015-05-20 05:24 UTC
I am trying to upload file using multer and express but it will give me a following error.
.write(string, encoding, offset, length) is deprecated. Use write(string[, offset[, length]][, encoding]) instead.

+node version is 12.3

I want to know how to resolve this issue.

**Comment by LinusU** [comment] 2015-05-20 06:51
Thank you for reporting this bug, could you run node with `--trace-deprecation` and paste the output here? This should let me know where the incorrect call is occurring.

**Comment by LinusU** [comment] 2015-05-20 06:52
E.g.

```sh
node --trace-deprecation index.js
```

**Comment by LinusU** [comment] 2015-05-25 13:28
I'm closing this since I'm fairly certain that this issue isn't in multer. Feel free to reopen with a trace printout.

**Closed by LinusU** 2015-05-25 13:28 UTC

**Comment by arifismail** [comment] 2015-06-01 16:23
damaan:testexpress arifm$ node --trace-deprecation app.js 
Express server listening on port 3000
Request handler 'start' was called.
GET / 200 6ms
Trace: .write(string, encoding, offset, length) is deprecated. Use write(string[, offset[, length]][, encoding]) instead.
    at Buffer.write (buffer.js:400:17)
    at MultipartParser.initWithBoundary (/Users/arifm/Documents/howTOs/node.js/testexpress/node_modules/express/node_modules/connect/node_modules/formidable/lib/multipart_parser.js:61:17)
    at IncomingForm._initMultipart (/Users/arifm/Documents/howTOs/node.js/testexpress/node_modules/express/node_modules/connect/node_modules/formidable/lib/incoming_form.js:308:10)
    at IncomingForm._parseContentType (/Users/arifm/Documents/howTOs/node.js/testexpress/node_modules/express/node_modules/connect/node_modules/formidable/lib/incoming_form.js:250:12)
    at IncomingForm.writeHeaders (/Users/arifm/Documents/howTOs/node.js/testexpress/node_modules/express/node_modules/connect/node_modules/formidable/lib/incoming_form.js:129:8)
    at IncomingForm.parse (/Users/arifm/Documents/howTOs/node.js/testexpress/node_modules/express/node_modules/connect/node_modules/formidable/lib/incoming_form.js:97:8)
    at /Users/arifm/Documents/howTOs/node.js/testexpress/node_modules/express/node_modules/connect/lib/middleware/multipart.js:125:12
    at noop (/Users/arifm/Documents/howTOs/node.js/testexpress/node_modules/express/node_modules/connect/lib/middleware/multipart.js:22:3)
    at multipart (/Users/arifm/Documents/howTOs/node.js/testexpress/node_modules/express/node_modules/connect/lib/middleware/multipart.js:76:5)
    at /Users/arifm/Documents/howTOs/node.js/testexpress/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:57:9
POST /upload 404 13ms

**Comment by LinusU** [comment] 2015-06-01 17:33
@arifismail Your stack trace shows that the problem is occurring in `formidable`. Would you please report the bug to them instead :)

**Comment by arifismail** [comment] 2015-06-01 19:24
Done!  Here is the link https://github.com/felixge/node-formidable/issues/336.  Hopefully it will be resolved soon.
