### ISSUE TITLE
filefilter throw error 

### ISSUE THREAD

**Issue by 39Er** [expressjs/multer#525] opened 2017-09-14 08:20 UTC
I found when I use fileFilter if it throws an error,the error handler can't catch it until the file finish uploading.How can I response the error when it throws immediately?

**Comment by 39Er** [comment] 2017-09-14 08:44
```
const upload = multer({
  storage: storage,
  limits: {
    fileSize: 3 * 1024 * 1024 //bytes
  },
  fileFilter: function (req, file, cb) {
    let originalname = file.originalname;
    let fileType = originalname.substr(originalname.lastIndexOf('.') + 1);
    if (fileType.indexOf('ppt') < 0 && fileType.indexOf('pdf') < 0) {
      return cb(new Error('file is invilid'));
    }
    return cb(null, true);
  }
});

const uploadFunc = upload.single('file');

module.exports.upload = function (req, res) {
  uploadFunc(req, res, function (err) {
    if (err) {
      req.logger.error(err);
      return res.jsonreq, res, '8', err.message);
    }
    res.json('success');
    
}

```

**Comment by jsieler** [comment] 2017-10-04 11:42
Having same problem... How just to break the upload?

**Comment by cemreinanc** [comment] 2017-10-19 10:01
We're having the same problem too.
We're using multer as an express middleware for a route.
Even if it throws an error the upload continues and we can see the error at the end of the upload.
If we don't want to accept the file because of its mimetype we have to wait until the upload finishes that makes no sense?

**Comment by HarshithaKP** [comment] 2019-10-07 13:54
@39Er  I am able to recreate the issue.
Based on my analysis fileFilter is applied at right time - i.e., as soon as the file reached its limit. But the user callback is not called until the `req` is finished, which happens only when the upload is completed. Here is the relevant code:

https://github.com/expressjs/multer/blob/59376904cf2317b3683368c8cbe3736356ffacd2/lib/make-middleware.js#L53

For me, this looks like a bug. However, copying @LinusU to confirm.

**Comment by jonchurch** [comment] 2020-01-18 22:44
Labeling and self assigning to look at this later

**Comment by jonchurch** [comment] 2020-01-18 22:48
Closing as duplicate of #344, please follow that issue

**Closed by jonchurch** 2020-01-18 22:48 UTC
Labels: bug, duplicate
