### ISSUE TITLE
How to check if image is not uploaded because multer does not give uploading field error

### ISSUE THREAD

**Issue by himanshubudhlakoti** [expressjs/multer#682] opened 2018-10-28 07:35 UTC
Hello All,
i am using following code of multer for uploading file and it works fine.
but when file is not uploaded then it does not give any error so how can i check multer error.
because i want to when my file is not uploaded then further operation should not be performed.

form below code where i can get multer error please let me know
```
var storage = multer.diskStorage({
  destination: function (req, file, cb) {
    console.log("FILE>>>" , file);
    cb(null, './public/images')
  },
  filename: function (req, file, cb) {
    cb(null, file.fieldname + '-' + Date.now()+path.extname(file.originalname));
  }
})

var upload = multer({ storage: storage }).single('file')

app.use("/uploadFile",upload,(req ,res , next)=>{
  console.log("req>>>>>","localhost:3000/images"+req.file.filename);
  res.send("localhost:3000/images/"+req.file.filename);
});


```

**Comment by LinusU** [comment] 2018-10-29 11:01
duplicate of #676

> You can check whether or not `file` is defined, and throw an error appropriately:
> 
> ```js
> if (!req.file) {
>   return next(new Error('Missing mandatory file'))
> }
> 
> // rest of the code...
> ```

**Closed by LinusU** 2018-10-29 11:01 UTC
