### ISSUE TITLE
connection reset on file upload with multer

### ISSUE THREAD

**Issue by nilaybrahmbhatt** [expressjs/multer#574] opened 2018-04-03 12:45 UTC
using latest multer with express and nginx server.
when i upload file it uploads successfully and completes its process but when file uploading completed server reset a connection and some process not completed.
I also put some APIs calling immediately after uploading an image but bcz of server reset API calls not working.

**Comment by LinusU** [comment] 2018-04-03 18:26
How are you running the server, is it possible that it's watching for changes to the files and restarting the server?

**Comment by nilaybrahmbhatt** [comment] 2018-04-04 04:28
@LinusU  yes on every file change my server reload. i am using express and nginx server. how can i stop reloading ?

**Comment by LinusU** [comment] 2018-04-04 10:29
The problem is that your file watcher is interpreting the created uploaded file as a file change, and then kills your server to start it again.

I would recommend using [forever](https://github.com/foreverjs/forever) or a similar tool to start your server (make sure to **not** use `-w`).

I will close this since it isn't a problem with multer per se, but I will still continue to answer any questions you may have 👍

**Closed by LinusU** 2018-04-04 10:29 UTC
