### ISSUE TITLE
Is there a way to handle random file fields names

### ISSUE THREAD

**Issue by gyzerok** [expressjs/multer#221] opened 2015-09-04 12:54 UTC
Hi there! I have a single endpoint (GraphQL) which handles forms submissions. But file fileds in form may differ. So I want to handle all those. I need something like
```javascript
multer().singleOrArray('*')
```
How to achieve this?

**Comment by BigstickCarpet** [comment] 2015-09-08 12:57
+1

**Comment by LinusU** [comment] 2015-09-19 22:26
Duplicate of #215

**Closed by LinusU** 2015-09-19 22:26 UTC

**Comment by LinusU** [comment] 2015-09-19 23:04
This can be fixed by #229
