### ISSUE TITLE
No way to enable/disable saving files with extensions.

### ISSUE THREAD

**Issue by abhishekdgeek** [expressjs/multer#469] opened 2017-03-15 08:12 UTC
Hi Team,

I am using MEAN stack provided by meanjs.org and they use .single() method for uploading profile images. I read https://github.com/expressjs/multer/issues/439 and this is good but then Internet Explorer is not smart enough to understand that the given file is an image. Can you please help me save files with extensions?

Thanks.

```
'use strict';

module.exports.profileUploadFileFilter = function (req, file, cb) {
  if (file.mimetype !== 'image/png' && file.mimetype !== 'image/jpg' && file.mimetype !== 'image/jpeg' && file.mimetype !== 'image/gif') {
    return cb(new Error('Only image files are allowed!'), false);
  }
  cb(null, true);
};


/**
 * Update profile picture
 */
exports.changeProfilePicture = function (req, res) {
  var user = req.user;
  var upload = multer(config.uploads.profileUpload).single('newProfilePicture');
  var profileUploadFileFilter = require(path.resolve('./config/lib/multer')).profileUploadFileFilter;

  // Filtering to upload only images
  upload.fileFilter = profileUploadFileFilter;

  if (user) {
    upload(req, res, function (uploadError) {
      if (uploadError) {
        console.log(uploadError);
        return res.status(400).send({
          message: 'Error occurred while uploading profile picture'
        });
      } else {
        user.profileImageURL = config.uploads.profileUpload.dest + req.file.filename;

        user.save(function (saveError) {
          if (saveError) {
            return res.status(400).send({
              message: errorHandler.getErrorMessage(saveError)
            });
          } else {
            req.login(user, function (err) {
              if (err) {
                res.status(400).send(err);
              } else {
                res.json(user);
              }
            });
          }
        });
      }
    });
  } else {
    res.status(400).send({
      message: 'User is not signed in'
    });
  }
};

```

**Comment by LinusU** [comment] 2017-03-15 08:39
I think that the problem is more likely that you aren't setting the correct `Content-Type` header when sending the image back, not that the file extension is missing...

How does the retrieval of the image look?

**Comment by jonchurch** [comment] 2020-01-25 21:00
Closing as resolved 🎉

**Closed by jonchurch** 2020-01-25 21:00 UTC
