### ISSUE TITLE
File Order

### ISSUE THREAD

**Issue by jsmunroe** [expressjs/multer#185] opened 2015-07-29 20:07 UTC
I was wondering if there is a way to maintain the original order of files when uploading an array of files while using upload.array().

**Comment by LinusU** [comment] 2015-07-29 20:11
When receiving files with `upload.array()`, `req.files` will be an array of the files that was uploaded. This array is ordered with the first file being the first file received.

The answer than should be that, yes, the files are presented in the original order.

I hope that this answers your question :)

**Comment by jsmunroe** [comment] 2015-07-29 20:20
In practice, these files are showing up in a random order even though I am requesting them in the same order. Perhaps I am not understanding how HTTP posts form-data requests. Is there no guarantee of file order within the HTTP specification?

**Comment by LinusU** [comment] 2015-07-29 20:24
How are you submitting? If via an html form, could you post the form for me here?

I think that the spec don't actually force the browser to send the fields in any specific order, but from my experience most browsers sends them in the order that they appear in the DOM.

**Comment by jsmunroe** [comment] 2015-07-30 14:58
For development I'm using Postman. I've checked it with Fiddler 2. It is sending in the prescribed order.

**Comment by LinusU** [comment] 2015-07-30 15:05
That should be the culprit than, nothing to be fixed in multer.

Feel free to reopen if you have more questions.

**Comment by jsmunroe** [comment] 2015-07-30 15:21
How is Postman the culprit? What I am saying is that the order is right according to Fiddler 2.

**Comment by LinusU** [comment] 2015-07-30 15:59
I'm sorry, I thought you meant that postman is sending them in an undefined order, and that it worked with fiddler 2. I don't have any experience with these tools...

Are you still having problems with `req.files` being populated in another order than the files arrive on the wire?

**Comment by jsmunroe** [comment] 2015-07-30 19:35
I am. I am trying to find a work around. I think multer is doing things asynchronously which is good node practice and therefore probably shouldn't be changed. I just need to be able to some how find the original order. 

I've asked the question on SO here: http://goo.gl/iM3AKc

**Comment by LinusU** [comment] 2015-07-31 03:59
@jsmunroe What storage engine are you using?

I cannot reproduce this and there is even a test which actually checks that the order is correct, and it passes on my machine and on Travis. Could you run the tests at your machine to see if it's failing.

**Comment by jsmunroe** [comment] 2015-07-31 12:55
I'm using the default. Here is my configuration. `root` is a directory on my server.

    var upload = multer({ dest: root });

**Comment by LinusU** [comment] 2015-07-31 13:24
Which platform are you on?

Could you please run the tests? Let me know if you need help on how to do that.

**Comment by jsmunroe** [comment] 2015-07-31 13:31
Yeah. I ran that test and it succeeded.  I just don't get it. I've turned off all other middleware except express. I'm also routing. I don't know if that changes things.

    router.post('/put', upload.array('useritem'), function (req, res, next) {  }

I'm running currently on my Windows development desktop. I'm running through Visual Studio 2015.

**Comment by LinusU** [comment] 2015-07-31 15:41
It's very strange, but scanning thru the code I did detect a possible race condition that maybe could cause this. It seems quite far fetched by hopefully I can get a test and a fix in during the weekend.

Basically what could happen is that the `fs.WriteStream` doesn't finish writing the file until the next file has already been fully processed by another `fs.WriteStream`. The other one doesn't even start until all the chunks have been read from the first one so I can only see this happening what very small files.

How large are your files?

**Comment by LinusU** [comment] 2015-08-06 20:35
@jsmunroe Great news! This should be fixed by 32590b66a26b778f0cc207d7cdc0f170356c7e7a, released as `1.0.3` on npm. :fire::fire::fire:

**Closed by LinusU** 2015-08-06 20:35 UTC
Labels: investigate
