### ISSUE TITLE
memoryStorage not creating buffer and instead saving it to tmp

### ISSUE THREAD

**Issue by dolivares** [expressjs/multer#209] opened 2015-08-19 06:02 UTC
Hello,

I'm doing a simple file upload which can be .docx, .doc or pdfs. 

```javascript
var storage = multer.memoryStorage({});
var upload = multer({storage: storage}).single('file');

app.post('/upload-resume', upload, function(req, res) {
    res.json(200);
});
```

When the above code is executed, the object isn't stored as "file" in the req as I expected. It's always stored as "files" and stored to tmp. Am I missing something? I'm doing this on express 3.4 and node 10.25.

**Comment by LinusU** [comment] 2015-09-19 22:32
The code you have posted should work, are you sure that this is the exact code that you are using? Could you please post the entire file?

**Comment by dlants** [comment] 2015-09-29 04:34
Hey dolivares, just ran into this issue myself. One thing you should check, is which version of express you're using.

Older versions of express come with their own form data middleware. I found out in my case, this was the case, and multer was working as expected.

Here's a relevant SO
http://stackoverflow.com/questions/11295554/how-to-disable-express-bodyparser-for-file-uploads-node-js

**Comment by LinusU** [comment] 2015-09-29 06:40
Cool, I'm closing this since the problem isn't in this module.

@dolivares Please upgrade to the latest express and avoid using `express.bodyParser()`.

**Closed by LinusU** 2015-09-29 06:40 UTC
