### ISSUE TITLE
Error: 413 Request Entity Too Large

### ISSUE THREAD

**Issue by suntong** [expressjs/multer#1166] opened 2022-12-04 18:16 UTC
> Same problem I can't exceed 1MB on a single() file upload despite setting 8MB:
>
>
```
const upload = multer({
  dest: '/tmp/uploads',
  limits: {
    fieldSize: 8 * 1024 * 1024,
  },
});

app.post('/messages/upload', upload.single('image'), async (req, res) => {
  // never get here as multer rejects as 413 (too large)
}
```
>
>`fileSize` not set as indicated as infinity, only `fieldSize` being limited to 1MB by default.
>
>I can confirm that defining `fileSize` lower than 1MB will result in files being rejected if they exceed the specified size, but it seems impossible to have anything greater than 1MB.

_Originally posted by @keiranmraine in https://github.com/expressjs/multer/issues/562#issuecomment-389642971_

**Comment by suntong** [comment] 2022-12-04 18:25
Reopening #562 as I'm having the exact same problem, yet all answers from it, as well as the answers from #344 #413&  #602, are not working for me.

I've provided a minimal reproduction case at

https://github.com/suntong/express-simple-example/tree/testing/upload/big  I.e.,
https://github.com/suntong/express-simple-example/blob/testing/upload/big/index.js

For such simple code, I'm getting the returned json as well as:

```
<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>openresty</center>
</body>
</html>
```

For my real code that did the actual uploading, I wasn't able to get the returned json but only the above html.

**Comment by suntong** [comment] 2022-12-04 18:42
I've also tried to add the following suggested "solution",

```
// fixing "413 Request Entity Too Large" errors
app.use(express.json({limit: "10mb", extended: true}))
app.use(express.urlencoded({limit: "10mb", extended: true, parameterLimit: 50000}))
```

But removed them as they are not working either.

**Comment by alamjamal** [comment] 2022-12-07 17:36
hi, can you specify which server are you using?

**Comment by suntong** [comment] 2022-12-07 20:15
I've provided a fully functional minimal reproduction case, anyone can give it a try to verify, if you want.

**Comment by LinusU** [comment] 2022-12-12 13:41
@suntong if you look at the html error page you will se an indication where the error originates from:

> `<hr><center>openresty</center>`

It seems like you are running [OpenResty](https://openresty.org/en/) in front of Node.js, and it's OpenResty that is limiting your post body.

Closing since the problem is outside of Multer

**Closed by LinusU** 2022-12-12 13:41 UTC

**Comment by suntong** [comment] 2022-12-12 15:49
I searched the whole project folder for KW: _"openresty"_ but found nothing. 
I've provided a fully functional minimal reproduction case, can anyone try it please?

**Comment by LinusU** [comment] 2022-12-12 16:50
@suntong I can upload a 13 MB file with your minimal reproduction case.

```sh
$ git clone git@github.com:suntong/express-simple-example.git
$ cd express-simple-example
$ npm install
$ npm start
```

(then in another terminal)

```sh
$ curl -X POST http://localhost:3399/upload -F file=@my-large-file.zip
```

**Comment by suntong** [comment] 2022-12-12 16:55
Oh, thanks a lot for trying @LinusU, 

would you verify your index.js is the same as that of
https://github.com/suntong/express-simple-example/blob/testing/upload/big/index.js
please?

As the index.js is in the `testing/upload/big` branch. Just want to double check as I don't see branch switching in your above commands. thx.

**Comment by LinusU** [comment] 2022-12-12 19:07
@suntong it's the same. I did forgot to put it in the above commands, but I did run it 👌 

Will update the comment...
