### ISSUE TITLE
Upload -- size limitation

### ISSUE THREAD

**Issue by joques** [expressjs/multer#562] opened 2018-02-18 05:32 UTC
Hi all,
is there a reason why multer won't upload a file that's more than 1MB?
Here's how multer is set up in my node server (using coffee script):

```coffee
storerOption         =
    destination: (req, file, cb) ->
        cb null, './uploads'
    filename: (req, file, cb) ->
        cb null, (file.originalname.split(" ")).join('')
limitOption =
    fileSize: 52428800
storer               = multer.diskStorage storerOption
uploader             = multer({ storage: storer, limits: limitOption })

app = express()
app.use(bodyParser.json({limit: '50mb'}))
app.use(bodyParser.urlencoded({limit: '50mb', extended: false}))
```

Did I get anything wrong?

**Comment by LinusU** [comment] 2018-02-23 11:15
There is no default file size limit, but there is a *field* size limit of 1MB. Is it possible that that is the one you are hitting?

Try adding `fieldSize: 52428800` in addition to `fileSize`

**Comment by kylerberry** [comment] 2018-03-12 14:43
@joques I'm having this exact issue. extending `fieldSize` and `fileSize` have no effect. Have you resolved your issue?

**Comment by keiranmraine** [comment] 2018-05-16 19:46
Same problem I can't exceed 1MB on a single() file upload despite setting 8MB:

```
const upload = multer({
  dest: '/tmp/uploads',
  limits: {
    fieldSize: 8 * 1024 * 1024,
  },
});

app.post('/messages/upload', upload.single('image'), async (req, res) => {
  // never get here as multer rejects as 413 (too large)
}
```

`fileSize` not set as indicated as infinity, only `fieldSize` being limited to 1MB by default.

6.1MB file I tested with:

https://static1.squarespace.com/static/54ef35d1e4b021bc7efe797f/t/5752f8507c65e46713913158/1465055400533/1-6.png?format=2500w

**Comment by endbay** [comment] 2018-07-13 08:05
If you are using nginx, you could try to add to your nginx config:

client_max_body_size 50M;

Default value is 1M

**Comment by terwi** [comment] 2018-07-16 14:31
Is it possible to add a folder size limitation in multer . in my case i am trying to limit the upload by the size of destination . to calculate the folder size i used the package "get-folder-size"

**Comment by me21** [comment] 2018-07-20 23:52
I have this issue too. Running express directly, no nginx. Here's my multer setup:
```
let storage = multer.memoryStorage();
let upload = multer({
    storage: storage,
    limits: {fieldSize: '50MB'}
});
```

**Comment by me21** [comment] 2018-07-20 23:58
I was getting this error too, but then I realized I was writing `fieldSize: '50MB'` instead of `fieldSize: 50 * 1024 * 1024`. The latter works for me. Got confused by multer's readme where the default fieldSize value is specified as 1MB.

**Comment by alfredd2001** [comment] 2019-02-10 19:42
I have added 50*1024*1024 to fileSize and to fieldSize and my image is uploaded but it is cropped almost all the bottom part and it ends up being 195.7kB long (not even 1MB) does someone have the same issue?

**Comment by diogolimafranco** [comment] 2019-05-27 11:53
In my case, simply adjust the upload size of the Nginx server by specifying the http {client_max_body_size 100M;}

https://www.tecmint.com/limit-file-upload-size-in-nginx/

**Comment by daweifeng** [comment] 2019-08-01 22:39
Same situation here. It turns out that it is the problem of Nginx's config. If you are running your app on AWS EB, here is a tutorial for setting the upload size on Nginx on AWS EB. 

https://stackoverflow.com/questions/18908426/increasing-client-max-body-size-in-nginx-conf-on-aws-elastic-beanstalk

**Comment by HarshithaKP** [comment] 2019-10-07 09:19
@joques is this still and issue for you ?

**Comment by ryhinchey** [comment] 2020-04-14 18:13
closing this issue as it's not a bug with multer

**Closed by ryhinchey** 2020-04-14 18:13 UTC

**Comment by kunalArya1** [comment] 2023-04-02 08:36
Field Size | Max field value size (in bytes) | 1MB
Given in docs of Multer js
![Screenshot (467)](https://user-images.githubusercontent.com/88975566/229341876-b735c213-7c50-4904-bd2c-1509d22d7c54.png)
