### ISSUE TITLE
Doesn't work with ajax

### ISSUE THREAD

**Issue by ryanaleksander** [expressjs/multer#420] opened 2016-11-26 01:48 UTC
I tried 3 approaches: sending JSON with axios, sending FormData with axios, sending FormData with XHR. None worked. `req.file` was undefined, and `req.body` was empty.

**server**
```
import multer from 'multer';
const upload = multer();

app.post('/api/posts/new', upload.single('image'), function(req, res, next){
	console.log(req.file);
	console.log(req.body);
	res.status(200).json(req.body);
})
```

I'm using KeystoneJS and serverside rendering React if any of that matters

**Comment by LinusU** [comment] 2016-11-26 15:09
I think that the problem is with your client code since this is working for other people, myself included.

Could you post the code that you are using to upload from the client?

**Comment by ryanaleksander** [comment] 2016-11-27 00:38
**1st approach**
```
export const submitNewPost = (post) => {
  let data = axios.post(NEW_POST_URL, post);

  return {
    ...
  }
}
```

**2nd approach**
```
export const submitNewPost = (post) => {
  let formData = new FormData();
  formData.append('image', post.image);
  // more appends
  
  let data = axios.post(NEW_POST_URL, formData);

  return {
    ...
  }
}
```

**3rd approach**
```
export const submitNewPost = (post) => {
  let formData = new FormData();
  formData.append('image', post.image);
  // more appends

  let xhr = new XMLHttpRequest();
  xhr.open('POST', NEW_POST_URL, true);
  let data = xhr.send(formData);

  return {
    ...
  }
}
```

In the 1st approach, `req.file` is undefined, and `req.body` is actually not empty. However, in the 2nd and 3rd approach, `req.body` is empty. I've checked and the client did send request with `Content-Type: multipart/form-data` and a payload

**Comment by r3wt** [comment] 2017-01-11 03:08
I have the exact same problem in express, using same http client, axios. i have checked the request payload and everything is correct.

**Comment by Muqito** [comment] 2017-01-15 12:13
I have a similar issue; but it works great on my computer not on my android phone though.

Unfortunately the debug tool for my android device doesn't work (old device) so I can't debug plugging it into my computer.

I use the 3rd approach @ryanaleksander wrote.

**Comment by AdamInTheOculus** [comment] 2017-02-09 17:35
I'm not sure if this helps, but I had the same issue in express, using `jQuery.ajax()` in the front-end.

I found two extra options were needed:

- `processData: false` This makes sure the data isn't transformed into a string.
- `contentType: false` This makes sure there is no content-header describing the data. I found having this option removed my `413 response code` (entity too large).

Hope this helps.

**Comment by Cherviakov** [comment] 2017-03-01 19:25
+1 with XMLHttpRequest

**Comment by eric-personal** [comment] 2017-04-26 19:29
I'm having the same issue. Has anyone solved this issue or found out if its axios or multer ?

**Comment by HarshithaKP** [comment] 2019-11-19 07:47
@ryanaleksander I think the problem is with passing headers (which has Content-Type,..)from client. I have written a working example using Axios client here : https://gist.github.com/HarshithaKP/ebc0e79800e5638fe827c157360378be 

Please let me know if it helps you in resolving your issue.
@eric-personal @r3wt

**Comment by LinusU** [comment] 2019-11-23 13:15
Seems like this was a client problem that can be solved by the code linked, happy to reopen if we should change something in Multer

**Closed by LinusU** 2019-11-23 13:15 UTC

**Comment by Libohan12** [comment] 2019-12-10 08:38
> @ryanaleksander我认为问题在于从客户端传递标头（具有Content-Type，..）。我在这里使用Axios客户端编写了一个工作示例：[https](https://gist.github.com/HarshithaKP/ebc0e79800e5638fe827c157360378be)：[//gist.github.com/HarshithaKP/ebc0e79800e5638fe827c157360378be](https://gist.github.com/HarshithaKP/ebc0e79800e5638fe827c157360378be)
> 
> 请让我知道它是否有助于您解决问题。
> @ eric-personal @ r3wt

This method works, because the file I uploaded is a FileList which results in a file of undeined.
thank

**Comment by Libohan12** [comment] 2019-12-10 08:39
> @ryanaleksander I think the problem is with passing headers (which has Content-Type,..)from client. I have written a working example using Axios client here : https://gist.github.com/HarshithaKP/ebc0e79800e5638fe827c157360378be
> 
> Please let me know if it helps you in resolving your issue.
> @eric-personal @r3wt
This method works, because the file I uploaded is a FileList which results in a file of undeined.
thank
