### ISSUE TITLE
how to reroll all file uploads incase of failure

### ISSUE THREAD

**Issue by rubiin** [expressjs/multer#864] opened 2020-03-28 07:58 UTC
i am using multiple file uploads using .array and would like to reroll all the uploaded files incase any file fails to upload. how can i achieve this?

**Comment by rubiin** [comment] 2020-03-28 18:56
@jonchurch

**Comment by jonchurch** [comment] 2020-03-28 21:36
I don't believe you can, you're not able to try and reprocess files during the same response after the upload has failed.

**Comment by rubiin** [comment] 2020-03-30 05:14
@jonchurch  is there a workaround?

**Comment by jonchurch** [comment] 2020-03-30 08:23
Can you help me understand your use case? Are you talking about salvaging the other files, or retrying the failed file without the user having t resubmit?

I dont think there is a workaround currently, when an error is encountered internally in the library we stop processing the submitted data.

**Comment by rubiin** [comment] 2020-03-31 07:02
i am uploading 4 files and would like to abort the whole upload operation incase any one of the file fails to upload. By abort I mean the uploaded files shoul also be deleted. Kind of like transactions in a database

**Comment by ryhinchey** [comment] 2020-04-14 18:30
this sounds like something that might be fit for a custom storage engine.  check out the docs here https://github.com/expressjs/multer/blob/master/StorageEngine.md#multer-storage-engine

**Comment by jonchurch** [comment] 2020-04-14 20:39
This issue, although different, reminded me of https://github.com/expressjs/multer/issues/259. I haven't devoted the time I intended to for either. 

@ryhinchey  @expressjs/triagers My main question is, can we reproduce both of these (the linked issue does have a repro case), and is this the behavior we expect? I've had the feeling that we are keeping files after certain fail states, when we shouldn't be. I haven't really done a thorough investigation, but if someone is up for it, I'd be happy to see it get done.

**Comment by JLuboff** [comment] 2020-04-15 17:44
While not an issue I've dealt with, I think a fairly simple workaround would be as such.

1. Form is submitted, multer uploads files to storage
2. As multer gives us `req.files`, check in your file save location if all files exist using `fs.readFile` (or whatever method you'd like).
3. If not all files exist, delete any existing files that were uploaded (or allow multer to overwrite them on next upload attempt) and send error code to original submission to than retry.

While I realize its not ideal, I believe it would be a workaround

**Comment by davidmashe** [comment] 2020-08-13 11:28
workarounds and alternatives were provided, no further activity. Closing issue.

**Closed by davidmashe** 2020-08-13 11:28 UTC
Labels: question
