### ISSUE TITLE
Wired error

### ISSUE THREAD

**Issue by flauc** [expressjs/multer#421] opened 2016-11-30 02:02 UTC
I get an error when using multer with Angular Universal. This repo precisely: 

https://github.com/angular/universal-starter

This is the error: 

```
TypeError: Cannot read property 'on' of undefined
    at new Multipart (C:\Users\Detectives\Desktop\Projects\universal-starter\node_modules\busboy\lib\types\multipart.js:288:5)
```

And this is the block that breaks: 

```js
  this.parser.on('drain', function() {
    self._needDrain = false;
    if (self._cb && !self._pause) {
      var cb = self._cb;
      self._cb = undefined;
      cb();
    }
  }).on('part', function onPart(part) {
    if (++self._nparts > partsLimit) {
      self.parser.removeListener('part', onPart);
      self.parser.on('part', skipPart);
      boy.hitPartsLimit = true;
      boy.emit('partsLimit');
      return skipPart(part);
    }
```

The same setup I'm using works perfectly fine in a simple envirement. If anyone could just point me in to a direction I'd appreciated it greatly since I've completely exhausted all of my ideas. 

Thank you 👍

**Comment by LinusU** [comment] 2016-11-30 08:14
Interesting, seems like the problem is in busboy...

You might be interested in trying out the alpha of 2.x, see #399

**Comment by flauc** [comment] 2016-11-30 09:41
Thanks having a look 👍 .

Unfortunately I still get the same error with 2.0.0-alpha.2. 

Do you maybe have an idea what might be causing the error, I just need something to focus on. I don't even know where to start looking.

**Comment by LinusU** [comment] 2016-11-30 10:02
Unfortunately I have no idea how this can be happening 🤔 It seems like the value of `this.parser` or `self.parser` is not what it's expecting it to be...

**Comment by ryhinchey** [comment] 2020-04-11 02:04
I'm going to go ahead and close this issue as it's not clear if the issue is with multer.

**Closed by ryhinchey** 2020-04-11 02:04 UTC
Labels: question
