### ISSUE TITLE
How to check if image submitted by user or not

### ISSUE THREAD

**Issue by sundarkrish** [expressjs/multer#677] opened 2018-10-22 09:26 UTC
When image field not specified in postman,the upload(req,res,function(err){ }) does nor throw any error.
The req.file is undefined and this is how I get to know that image is not submitted.Also the filefilter and destination methods are not called at this time.
How to do validation checks on text fields and file fields ?

**Comment by LinusU** [comment] 2018-10-29 11:00
duplicate of #676

**Closed by LinusU** 2018-10-29 11:00 UTC
