### ISSUE TITLE
Body parser, req.body is instantiated on null prototype

### ISSUE THREAD

**Issue by Maximization** [expressjs/multer#171] opened 2015-07-22 12:04 UTC
In my project I'm using multer together with Joi to validate incoming body requests. I've noticed this was giving me an error of undefined while other non multipart type requests going through body-parser worked just fine. I managed to track the error to the fact that Joi uses hasOwnProperty on req.body while multer instantiates req.body on null as Object.create(null), this can be found [here](https://github.com/expressjs/multer/blob/master/lib/make-middleware.js#L28). Therefore none of the global object functions are available to use on req.body.

It might be nice to instantiate req.body as an object literal `{}` or `Object.create(Object.prototype)` to have those methods available on the parsed body for further use down the middleware chain. Body parser already does this as you can see [here](https://github.com/expressjs/body-parser/blob/master/lib/types/json.js#L96).

Let me know what you think and if you agree. I can submit a quick PR if you want to.

**Comment by LinusU** [comment] 2015-07-22 19:35
Hmm, the reason I did this was specifically not to have the native prototype on it. The problem with letting the prototype be on it is that any user is free to at will overwrite those properties. E.g. a user could send a key called `hasOwnProperty` and thus overwrite that function.

Here are some good reading on the topic: [Blog post by Guillermo Rauch](http://www.devthought.com/2012/01/18/an-object-is-not-a-hash/), [Article on 2ality](http://www.2ality.com/2012/01/objects-as-maps.html)

I'm feeling that the correct solution here would be to patch Joi not to use `hasOwnProperty` from the provided user input, but instead using it from the native object prototype.

```javascript
function hasOwnProperty (obj, prop) {
  return Object.prototype.hasOwnProperty.call(obj, prop)
}
```

I'm very confident that they would accept the patch since it's made for validating user input, and user input can always contain strange stuff. In the worst case scenario here, an end user could trick the system into executing code (although quite unlikely, it's definitely possible).

**Comment by LinusU** [comment] 2015-07-22 19:51
See hapijs/joi#693

**Comment by LinusU** [comment] 2015-07-22 20:41
Hmm, I actually believe that the problem is not wit joi but with something else. Are you maybe using [express-joi](https://github.com/petreboy14/express-joi)?

**Comment by Maximization** [comment] 2015-07-22 22:09
Good article, I agree with you on the topic that we should never trust user input. I like the proposed solution of using inherited properties on the native object. Thanks for spending the time trying to fix it on their end.

I'm using [hapijs/joi](https://github.com/hapijs/joi), and the problem does lie on their end. More specifically it has to do with their object validation methods. In my use case I'm using the .nand function. [Here](https://github.com/hapijs/joi/blob/master/lib/object.js#L617) is where .hasOwnProperty is called on the body parsed from the request object. As you can see this happens in more places throughout the file.

We should reopen [hapijs/joi#693](https://github.com/hapijs/joi/issues/693) and see what they think of it. I'll submit a failing test tomorrow.

**Comment by Marsup** [comment] 2015-07-22 22:32
Fixed by 6.6.1.

**Comment by Maximization** [comment] 2015-07-23 06:44
Can confirm this is now fixed after updating Joi. Great response guys!

**Closed** 2015-07-23 06:44 UTC

**Comment by LinusU** [comment] 2015-07-23 08:32
Thank you for your help @Marsup :+1:
